config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :feedbacks, except: %i[edit update destroy]
  resources :contacts
  root to: "contacts#index"
  get "/contact_search", to: "contacts#contact_search"
  get "/departament_search", to: "departaments#departament_search"
  get "/departaments", to: "departaments#index"
  get 'export', to: 'contacts#export_to_excel'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :departament

  validates :name, :telephone, :email, presence: true, uniqueness: true

  def as_json(options={})
    { :name => self.name,
    :email => self.email,
  :telephone => self.telephone } 
  end
end

app/models/departament.rb
class Departament < ApplicationRecord
  has_many :contacts, dependent: :destroy

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  EMAIL_REGEXP = /\A[a-z0-9\.\-]+@[a-z0-9]+\.[a-z]+\z/

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: EMAIL_REGEXP }
  validates :message, :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: %i[ show update edit destroy ]

  def index
    @contacts = Contact.includes(:departament).order("departaments.title ASC").page(params[:page]).per(13)
  end

  def contact_search
    contacts = Contact.where("name = ? or email = ?", params[:search], params[:search]) if params[:search].present?

    render json: contacts
  end

  def export_to_excel
    @contacts = Contact.includes(:departament).order("departaments.title ASC") # Данные, которые мы хотим выгрузить в Excel файл

    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="all_contacts.xlsx"'
      }
    end
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to departaments_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to departaments_path, notice: "Контакт обновлён"
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js # добавляем эту строку для создания файлов.js.erb
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:departament_id, :name, :telephone, :email)
  end

  def set_contact
    @contact = Contact.find(params[:id])
  end
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @departaments = Departament.all
  end

  def departament_search
    @departament = Departament.find(params[:search])
    @departaments = @departament.contacts.page(params[:page]).per(5)

  rescue ActiveRecord::RecordNotFound
    flash[:notice] = "Вы не ввели значение"
    redirect_to root_url
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        FeedbackMailer.new_feedback(@feedback).deliver_now
        format.html { redirect_to feedback_url(@feedback), notice: "Feedback was successfully created." }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to feedback_url(@feedback), notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:title, :name, :email, :message)
    end
end

app/views/contacts/_contact.html.erb
<tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.telephone %></td>
      </tr>

app/views/contacts/create.js.erb
// Получить JSON-данные от сервера
const data = <%= raw @contact.to_json %>;

// Найти или создать HTML-элемент для отображения данных
let objectElement = document.getElementById(`object-${data.id}`);
if (!objectElement) {
  objectElement = document.createElement('div');
  objectElement.id = `object-${data.id}`;
  document.body.appendChild(objectElement);
}

// Обновить содержимое элемента
objectElement.innerHTML = `
  <h1>${data.name}</h1>
  <p>${data.description}</p>
`;

app/views/contacts/destroy.js.erb
element = document.getElementById("contact_<%= @contact.id %>");
element.remove();

app/views/contacts/edit.html.erb
<h1>Редактирование</h1>
<%= form_with(model: @contact, local: true) do |form| %>    
   
   <div>
    <p><%= form.label :"Имя" %></p>
    <p><%= form.text_field :name %></p>
  </div>

  <div>
    <p><%= form.label :"Телефон" %></p>
    <p><%= form.text_field :telephone %></p>
  </div>

  <div>
    <p><%= form.label :"Email" %></p>
    <p><%= form.text_field :email %></p>
  </div>

  <div class="field">
    <%= form.label :departament_id, "Отдел" %>
    <%= form.select :departament_id,
                    Departament.all.map { |dept| [dept.title, dept.id] }, {},
                    { required: true, include_blank: "Select Department" } %>
  </div>

  <div class="actions">
    <p><%= form.submit "Сохранить" %></p>
  </div>
<% end %>

app/views/contacts/index.html.erb
<div id="contacts"></div> <!-- элемент, в который мы будем добавлять таблицу -->

<div id="contact">

<table>
  <thead>
    <tr>
      <th>ФИО</th>
      <th>Email</th>
      <th>ОТДЕЛ</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.departament.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @contacts%>
</div>

app/views/contacts/new.html.erb
<h1>Новый контакт</h1>
<%= form_with(model: @contact, url: @contact.new_record? ? contacts_path : contact_path(@contact), remote: true, local: true) do |form| %>    
   
   <div>
    <p><%= form.label :"Имя" %></p>
    <p><%= form.text_field :name%></p>
  </div>

  <div>
    <p><%= form.label :"Телефон" %></p>
    <p><%= form.text_field :telephone %></p>
  </div>

  <div>
    <p><%= form.label :"Email" %></p>
    <p><%= form.text_field :email %></p>
  </div>

  <div class="field">
    <%= form.label :departament_id, "Отдел" %>
    <%= form.select :departament_id,
                    Departament.all.map { |dept| [dept.title, dept.id] }, {},
                    { required: true, include_blank: "Select Department" } %>
  </div>

  <div class="actions">
    <p><%= form.submit "Создать" %></p>
  </div>
<% end %>

app/views/departaments/departament_search.html.erb
<div id="contacts"></div> <!-- элемент, в который мы будем добавлять таблицу -->

<div id="search-results">

<h2><%= @departament.title%></h2>

<table>
  <thead>
    <tr>
      <th>ФИО</th>
      <th>Email</th>
      <th>Телефон</th>
    </tr>
  </thead>
  <tbody>
  <%=render @departaments %>
     
  </tbody>
</table>

<%= paginate @departaments%> 
</div>

app/views/departaments/departament_search.js.erb
$("#search-results").html("<%= escape_javascript(render "contacts/contact") %>");

app/views/departaments/index.html.erb
<div id="contacts"></div> <!-- элемент, в который мы будем добавлять таблицу -->

<% @departaments.each do |departament|%>
  <%if departament.contacts.any? %>
    <b><p><%= departament.title%></p></b>
  <%end%>

  <%departament.contacts.each do |contact|%>
    <p id="contact_<%= contact.id %>" >
      <%=contact.name%>: 
      тел. <%= contact.telephone%>, email "<%= contact.email%>"
      <% if user_signed_in? && current_user.status == 1%>
        <%= link_to "Редактировать", edit_contact_path(contact)%>
        <%= link_to "Удалить", contact_path(contact.id), method: :delete, remote: true %>
      <%end%>
    </p>
  <%end%>
<%end%>

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback, local: true) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :"Ваше ФИО" %><p>
    <p><%= form.text_field :name, required: true %></p>
  </div>

  <div class="field">
    <p><%= form.label :"Название заявки" %></p>
    <p><%= form.text_field :title, required: true %></p>
  </div>

  <div class="field">
    <p><%= form.label :email %></p>
    <p><%= form.email_field :email, required: true %></p>
  </div>

  <div class="field">
    <p><%= form.label :"Текст заявки" %></p>
    <p><%= form.text_area :message, required: true %></p>
  </div>

  <div class="actions">
    <%= form.submit "Отправить"%>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Редактирование</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Все заявки</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td style="text-align: left"><%= link_to "Заявка №#{feedback.id} #{feedback.title}", feedback %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Создать заявку', new_feedback_path, method: :get %>

<div id="contacts"></div> <!-- элемент, в который мы будем добавлять таблицу -->

app/views/feedbacks/new.html.erb
<h1 style="background-color: #9bc77e; margin-bottom: 3px">Новая заявка</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<h3>Заявка № <%=@feedback.id%></h3>

<p><%=@feedback.name%></p>

<p><%=@feedback.title%></p>

<p><%=@feedback.message%></p>

<%= link_to 'Back', feedbacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="background2" >
  <head>
    <title>Request</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  

  <div>
    <div class="topnav">
      
      <div class="search-form">
          <%= text_field_tag :search, nil, placeholder: "Введите ФИО или email ..."%>
          <button onclick="search()">Поиск</button>
      </div>

      <div class="search-form">
        <%= form_tag departament_search_path, method: :get do %>
            <%= select_tag :search, 
            options_for_select([["Введите отдел", ""],["Oтдел снабжения", 1], ["Отдел кадров", 2],
             ["Архив", 3], ["Бухгалтерия", 4]]) %>
          <%= submit_tag "Search" %>
        <% end %>
      </div>
      
      <%=link_to "Главная", root_path, style: "margin-left: -80px"  %>
      <%=link_to "Заявки", feedbacks_path%>
      <%=link_to "Контакты", departaments_path %>
      
      <% if user_signed_in? && current_user.status == 1 %>
        <div style="display: inline-block; vertical-align: middle;"><%= button_to "Создать контакт", new_contact_path, method: :get %></div>
      <% end %>

      <%= link_to "Выйти", destroy_user_session_path, method: :delete, class:"align-right"%>

    </div>
   
    <p id="notice"><%= notice %></p>
    <p style="text-align: right; margin: 0"><%= link_to 'Экспортировать.xlsx', export_path(format: :xlsx) %></p>

    <div class="background">
      <body >
        
        <%= yield %>
      </body>
    <div>
  </div>
</html>